from server_flask.db import db
from datetime import datetime


class Products(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    article = db.Column(db.String(150), unique=True)
    product_name = db.Column(db.String(150))
    name_official = db.Column(db.String(150))
    description = db.Column(db.String(300))
    photo_1 = db.Column(db.String(300))
    photo_2 = db.Column(db.String(300))
    photo_3 = db.Column(db.String(300))
    photo_4 = db.Column(db.String(300))
    photo_5 = db.Column(db.String(300))
    photo_6 = db.Column(db.String(300))
    photo_7 = db.Column(db.String(300))
    price = db.Column(db.Numeric(precision=8, scale=2))
    opt_1 = db.Column(db.Numeric(precision=8, scale=2))
    opt_2 = db.Column(db.Numeric(precision=8, scale=2))
    opt_3 = db.Column(db.Numeric(precision=8, scale=2))
    opt_4 = db.Column(db.Numeric(precision=8, scale=2))
    opt_5 = db.Column(db.Numeric(precision=8, scale=2))
    opt_6 = db.Column(db.Numeric(precision=8, scale=2))
    opt_7 = db.Column(db.Numeric(precision=8, scale=2))
    opt_8 = db.Column(db.Numeric(precision=8, scale=2))
    opt_9 = db.Column(db.Numeric(precision=8, scale=2))
    opt_10 = db.Column(db.Numeric(precision=8, scale=2))
    opt_11 = db.Column(db.Numeric(precision=8, scale=2))
    opt_12 = db.Column(db.Numeric(precision=8, scale=2))
    quantity = db.Column(db.Integer)
    body_product_price = db.Column(db.Numeric(precision=8, scale=2))
    orders = db.relationship('Orders', secondary='ordered_product', overlaps='ordered_product,orders,products')
    ordered_product = db.relationship('OrderedProduct', back_populates='products')
    product_analitic = db.relationship('ProductAnalitic', back_populates='products')
    arrival = db.relationship('Arrival', back_populates='products')
    product_relate = db.relationship('ProductRelate', back_populates='products')
    project_id = db.Column(db.Integer, db.ForeignKey(
        'project.id', name='fk_products_project_id'))
    
